name: Build Android APK

on:
  push:
    branches: [ "main" ] # Cambia "main" por el nombre de tu rama principal
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos a Gradlew
      run: chmod +x gradlew

    - name: Compilar APK de Debug
      run: ./gradlew assembleDebug

    - name: Listar archivos para verificar ruta
      run: find . -name "*.apk"

    - name: Subir el APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/*.apk" # Esto buscará cualquier archivo .apk en cualquier carpeta
